name: CI
on:
  push:
    branches: ["develop"]
  pull_request:
    branches: ["develop"]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Build
        run: |
          npm install
          npm run build
  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install dependencies
        run: npm install
      # - name: Run Tests
      # run: npm run test
  deploy:
    name: Deploying
    needs: [test]
    runs-on:
      ubuntu-latest
      # Only run this step if the branch is develop
    if: github.ref == 'refs/heads/develop'
    steps:
      - name: Deploying to Render
        env:
          deploy_url: ${{ secrets.RENDER_DEPLOY_HOOK_URL }}
        run: |
          curl "$deploy_url"
